### ISSUE TITLE
Cant register 

### ISSUE THREAD

**Issue by piyusss11** [rishyym0927/Affinity_frontend#8] opened 2024-09-29 17:50 UTC
clicking on Register is not working. It neither directs to the login or profile page nor gives any error.

attached a video below for reference.
https://github.com/user-attachments/assets/5deabf11-c4c4-490f-967b-6ce009003707

**Comment by krishaga** [comment] 2024-09-29 18:16
Hey I think I got this, can you assign it to me.

**Comment by Sidharth-Singh10** [comment] 2024-09-29 20:33
Hey @piyusss11, it looks like the issue is occurring because the frontend isn't connected to the backend. 
You can find the backend repository here: [Affinity-backend](https://github.com/Sidharth-Singh10/Affinity-backend).

Please consider coming up with a solution to propagate the error to the user when this issue occurs.

**Closed** 2024-09-30 07:18 UTC
